apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellodocker
  labels:
    app: hellodocker
    tier: frontend
    monitored: "true"
spec:
  replicas: 3 #OR your desired number of replicas
  selector:
    matchLabels:
      app: hellodocker
  template:
    metadata:
      labels:
        app: hellodocker
        tier: frontend
        monitored: "true"
    spec:
      containers:
        - name: hellodocker
          image: jonesjamescompsci/hellodocker:76f9b3611f814395b09dfd1b8dcbec35184347d6 #Replace with your image <dockerusername>/hellodocker:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: NAME
              value: "James Jones from minikube, Kubernetes, and ArgoCD"
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 30
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 30
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2" 
